source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
#inhibit_all_warnings!

def common
    pod 'WeexSDK', :path=>'../sdk/'
    
    pod 'SDWebImage', '3.7.5'
    pod 'SocketRocket', '0.4.2'
    pod 'ATSDK-Weex', '0.0.1'
    pod 'AFNetworking', '~> 3.1.0'
    pod 'PPNetworkHelper'
end

target 'YJPT' do
    common
end

target 'YJPTUITests' do
    common
end
